#!/usr/bin/env php
<?php
require __DIR__.'/database/db.php';

// Basic CLI router
$cmd = $argv[1] ?? null;

if ($cmd === 'make') {
    $name = $argv[2] ?? 'NewMigrationTable';
    
    // Convert PascalCase to snake_case
    $name = strtolower(preg_replace('/([a-z])([A-Z])/', '$1_$2', $name));
    
    // Remove 'Table' from the end if present
    if (str_ends_with($name, '_table')) {
        $newName = substr($name, 0, -6);
    } else {
        echo "Migration name should be in the format 'UsersTable'";
        exit(1);
    }

    $filename = date('Y_m_d_His') . "_create_$name.php";
    $template = <<<PHP_EOL
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Capsule\Manager as Capsule;

return new class extends Migration {
    public function up() {
        Capsule::schema()->create('{$newName}', function (Blueprint \$table) {
            \$table->id();
            \$table->string('name');
            \$table->timestamps();
        });
    }
    public function down() {
        Capsule::schema()->dropIfExists('{$newName}');
    }
};
PHP_EOL;

   $dirName = __DIR__ . "/database/migrations";
   if (!is_dir($dirName)) mkdir($dirName, 0, true);

   file_put_contents("$dirName/$filename", $template);
   echo "Created: database/migrations/$filename\n";
}

if ($cmd === 'migrate') {
    foreach (glob(__DIR__.'/database/migrations/*_table.php') as $file) {
        echo "Running: $file\n";
        $migration = require $file;
        $migration->up();
    }
}

if ($cmd === 'rollback') {
    foreach (array_reverse(glob(__DIR__.'/database/migrations/*_table.php')) as $file) {
        echo "Rolling back: $file\n";
        $migration = require $file;
        $migration->down();
    }
}
